# Generated by Django 2.2.1 on 2019-05-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '网友建议',
                'verbose_name_plural': '网友建议',
            },
        ),
    ]
