# Generated by Django 2.2.1 on 2019-05-18 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20190517_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
