# Generated by Django 2.2.1 on 2019-05-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votetest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='用户姓名')),
                ('pwd', models.CharField(max_length=30, verbose_name='用户密码')),
            ],
        ),
    ]
